#订阅链接集
p: &p
 type: http
 interval: 28800
 #proxy: DIRECT
 override:
  udp: true
  ip-version: ipv4-prefer
  skip-cert-verify: false

#订阅链接
proxy-providers:
 provider1:
  <<: *p
  url: "&flag=meta&types=all"


#特殊节点集
u: &u
 type: url-test
 url: 'https://www.gstatic.com/generate_204'
 interval: 300
 #tolerance: 50
 timeout: 2000
 lazy: false
 include-all-providers: true

#规则集
r: &r
 type: http
 interval: 28800
 #proxy: DIRECT

#主配置
allow-lan: true
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
profile: # 存储 select 选择记录
 store-selected: true
 store-fake-ip: false
dns:
 enable: true
 ipv6: true
 enhanced-mode: fake-ip
 fake-ip-range: 198.18.0.1/16
 default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
 nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - 8.8.8.8
  - 1.1.1.1
 nameserver-policy:
  "rule-set:Mydirect,Direct1,Direct2":
   - 119.29.29.29
   - 223.5.5.5
  "rule-set:Myproxy,GFW,Proxy1,Proxy2":
   - 8.8.8.8
   - 1.1.1.1
 proxy-server-nameserver:
  - 119.29.29.29
  - 223.5.5.5
sniffer:
 enable: true
 override-destination: false
 sniff:
  HTTP:
   ports: [80, 8080-8880]
   override-destination: true
  TLS:
   ports: [443, 8443]
  QUIC:
   ports: [443, 8443]
mixed-port: 7890
proxy-groups:
 - name: "代理"
   type: select
   proxies:
    - DIRECT
    - url-test 香港
    - url-test 日本
    - url-test 美国
   use:
    - provider1
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png
 - name: "GPT"
   type: select
   proxies:
    - 直连
    - 代理
    - url-test 香港
    - url-test 日本
    - url-test 美国
   use:
    - provider1
   icon: https://github.com/NB921/picture/raw/main/chatgpt.png
 - name: "游戏"
   type: select
   proxies:
    - DIRECT
    - 代理
    - url-test 香港
    - url-test 日本
    - url-test 美国
   use:
    - provider1
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Game.png
 - name: "平台游戏下载"
   type: select
   proxies:
    - DIRECT
    - 代理
    - 游戏
    - url-test 香港
    - url-test 日本
    - url-test 美国
   use:
    - provider1
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Download.png
 - name: "直连"
   type: select
   proxies:
    - DIRECT
    - 代理
    - 游戏
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Proxy.png
 - name: "未知"
   type: select
   proxies:
    - 直连
    - 代理
    - 游戏
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Stack.png
 - name: "广告"
   type: select
   proxies:
    - REJECT
    - 直连
    - 代理
    - 游戏
   icon: https://github.com/NB921/picture/raw/main/AD3.png
 - name: "url-test 香港"
   <<: *u
   filter: "^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:港|香港|HongKong|HK|Hong Kong)).*$"
   #exclude-filter:""
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png
 - name: "url-test 日本"
   <<: *u
   filter: "^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)).*$"
   #exclude-filter:""
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png
 - name: "url-test 美国"
   <<: *u
   filter: "^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z]))).*$"
   #exclude-filter:""
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png
rules:
 - RULE-SET,Download,DIRECT
 - AND,((NOT,((RULE-SET,AD-direct))),(RULE-SET,AD)),广告

 - RULE-SET,GameDownload,平台游戏下载
 - RULE-SET,Mygames,游戏
 - RULE-SET,GPT,GPT
 - RULE-SET,Telegram,代理

 - RULE-SET,Myproxy,代理
 - RULE-SET,Mydirect,直连
 - RULE-SET,GFW,代理
 - RULE-SET,Proxy1,代理
 - RULE-SET,Proxy2,代理
 - RULE-SET,Direct1,直连
 - RULE-SET,Direct2,直连

 - RULE-SET,ip-cn,直连

 - MATCH,未知
rule-providers:
 AD-direct:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/Direct/Direct.yaml"
  behavior: classical
  format: yaml

 AD:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Domain.yaml"
  behavior: domain
  format: yaml

 Download:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Download/Download.yaml"
  behavior: classical
  format: yaml

 GameDownload:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Game/GameDownload/GameDownload.yaml"
  behavior: classical
  format: yaml

 Mydirect:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Mydirect.yaml"
  behavior: classical
  format: yaml

 Myproxy:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Myproxy.yaml"
  behavior: classical
  format: yaml

 Mygames:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Mygames.yaml"
  behavior: classical
  format: yaml

 Telegram:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Telegram/Telegram.yaml"
  behavior: classical
  format: yaml

 GPT:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/OpenAI/OpenAI.yaml"
  behavior: classical
  format: yaml

 GFW:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/gfw.mrs"
  behavior: domain
  format: mrs

 Proxy1:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/geolocation-!cn.mrs"
  behavior: domain
  format: mrs

 Proxy2:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/tld-!cn.mrs"
  behavior: domain
  format: mrs

 Direct1:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/geolocation-cn.mrs"
  behavior: domain
  format: mrs

 Direct2:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/tld-cn.mrs"
  behavior: domain
  format: mrs

 ip-cn:
  <<: *r
  url: "https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cn.mrs"
  behavior: ipcidr
  format: mrs
