#订阅链接集
p: &p
 type: http
 interval: 28800
 #proxy: DIRECT
 override:
  udp: true
  skip-cert-verify: false
 exclude-filter: "剩余|流量|套餐|到期|使用|文档|最新|网址|官网|更新|订阅|地址"

#订阅链接
proxy-providers:
 provider1:
  <<: *p
  url: "&flag=meta&types=all"

#规则集
r: &r
 type: http
 interval: 28800
 #proxy: DIRECT

#主配置
allow-lan: true
mode: rule
log-level: info
ipv6: true
disable-keep-alive: true
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
profile: # 存储 select 选择记录
 store-selected: true
mixed-port: 7890
dns:
  enable: true
  cache-algorithm: arc
  ipv6: true
  enhanced-mode: redir-host
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
  skip-src-address:
    - 192.168.0.3/32
  skip-dst-address:
    - 192.168.0.3/32
proxy-groups:
 - name: "PROXY"
   type: select
   proxies:
    - DIRECT
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png
 - name: "Unlock"
   type: select
   proxies:
    - DIRECT
    - PROXY
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Available_1.png
 - name: "Download"
   type: select
   proxies:
    - DIRECT
    - PROXY
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Download.png
 - name: "CN"
   type: select
   proxies:
    - DIRECT
    - PROXY
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Proxy.png
 - name: "No match"
   type: select
   proxies:
    - DIRECT
    - PROXY
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Stack.png
 - name: "AD"
   type: select
   proxies:
    - REJECT
    - DIRECT
    - PROXY
   icon: https://github.com/NB921/picture/raw/main/AD3.png
rules:
 - AND,((DST-PORT,443),(NETWORK,udp)),REJECT
 - AND,((NOT,((RULE-SET,AD!))),(RULE-SET,AD)),AD

 - RULE-SET,download,Download
 - RULE-SET,unlock,Unlock
 - RULE-SET,proxy,PROXY
 - RULE-SET,direct,CN

 - RULE-SET,Proxy1,PROXY
 - RULE-SET,Direct1,CN

 - RULE-SET,Cn1,CN
 - RULE-SET,Cn2,CN

 - MATCH,No match
rule-providers:
 AD:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Classical_No_Resolve.yaml"
  behavior: classical
  format: yaml

 AD!:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/Direct/Direct_No_Resolve.yaml"
  behavior: classical
  format: yaml

 download:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/download.list"
  behavior: classical
  format: text

 unlock:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/unlock.list"
  behavior: classical
  format: text

 proxy:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/proxy.list"
  behavior: classical
  format: text

 direct:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/direct.list"
  behavior: classical
  format: text

 Proxy1:
  <<: *r
  url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyGFWlist.list"
  behavior: classical
  format: text

 Direct1:
  <<: *r
  url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaDomain.list"
  behavior: classical
  format: text

 Cn1:
  <<: *r
  url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaIp.list"
  behavior: classical
  format: text

 Cn2:
  <<: *r
  url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaIpV6.list"
  behavior: classical
  format: text
