#订阅链接集
p: &p
 type: http
 interval: 28800
 #proxy: DIRECT
 override:
  udp: true
  skip-cert-verify: false
 exclude-filter: ":|：|!|！"

#订阅链接
proxy-providers:
 provider1:
  <<: *p
  url: "&flag=meta&types=all"

#规则集
r: &r
 type: http
 interval: 28800
 #proxy: DIRECT

#主配置
allow-lan: true
mode: rule
log-level: info
ipv6: true
disable-keep-alive: true
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: false
find-process-mode: strict
profile: # 存储 select 选择记录
 store-selected: true
mixed-port: 7890
proxy-groups:
 - name: "PROXY"
   type: select
   proxies:
    - DIRECT
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png
 - name: "GPT"
   type: select
   proxies:
    - DIRECT
    - PROXY
   include-all-providers: true
   icon: https://github.com/NB921/picture/raw/main/chatgpt.png
 - name: "游戏"
   type: select
   proxies:
    - DIRECT
    - PROXY
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Game.png
 - name: "平台游戏下载"
   type: select
   proxies:
    - DIRECT
    - 游戏
   include-all-providers: true
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Download.png
 - name: "国内网站"
   type: select
   proxies:
    - DIRECT
    - PROXY
   icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Proxy.png
 - name: "广告"
   type: select
   proxies:
    - REJECT
    - DIRECT
    - PROXY
   icon: https://github.com/NB921/picture/raw/main/AD3.png
rules:
 - AND,((NOT,((RULE-SET,AD!))),(RULE-SET,AD)),广告
 - RULE-SET,Download,DIRECT
 - RULE-SET,Private,DIRECT

 - RULE-SET,GameDownload,平台游戏下载
 - RULE-SET,Mygames,游戏
 - RULE-SET,GPT,GPT

 - RULE-SET,Myproxy,PROXY
 - RULE-SET,Mydirect,国内网站
 - RULE-SET,Proxy1,PROXY
 - RULE-SET,Direct1,国内网站
 - RULE-SET,Cn1,国内网站
 - RULE-SET,Cn2,国内网站

 - MATCH,PROXY
rule-providers:
 AD:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Classical.yaml"
  behavior: classical
  format: yaml

 AD!:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/AdGuardSDNSFilter/Direct/Direct.yaml"
  behavior: classical
  format: yaml

 Download:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
  behavior: classical
  format: yaml

 Private:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
  behavior: domain
  format: yaml

 GameDownload:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Game/GameDownload/GameDownload.yaml"
  behavior: classical
  format: yaml

 Mygames:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Mygames.yaml"
  behavior: classical
  format: yaml

 GPT:
  <<: *r
  url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/OpenAI/OpenAI.yaml"
  behavior: classical
  format: yaml

 Myproxy:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Myproxy.yaml"
  behavior: classical
  format: yaml

 Mydirect:
  <<: *r
  url: "https://github.com/Noah-Oliver/proxy-rule/raw/main/rule/clash/Mydirect.yaml"
  behavior: classical
  format: yaml

 Proxy1:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
  behavior: domain
  format: yaml

 Direct1:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
  behavior: domain
  format: yaml

 Cn1:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
  behavior: ipcidr
  format: yaml

 Cn2:
  <<: *r
  url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
  behavior: ipcidr
  format: yaml
