# ============================================================
# Shadowrocket Configuration
# Clash -> Shadowrocket
# ============================================================

[General]
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = 119.29.29.29,223.5.5.5,180.76.76.76,180.184.1.1
fallback-dns-server = system
ipv6 = true
prefer-ipv6 = false
dns-fallback-system = true
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true


[Proxy Group]

# 核心策略组
国外 = select,香港,新加坡,其他
解锁 = select,香港,新加坡,其他
国内 = select,DIRECT,国外
广告 = select,REJECT,DIRECT,国外

# 地区策略组
香港 = select,url=http://www.gstatic.com/generate_204,interval=600,timeout=5,tolerance=50,policy-regex-filter=🇭🇰|HK|hk|Hong Kong|Hongkong|香港|港
新加坡 = select,url=http://www.gstatic.com/generate_204,interval=600,timeout=5,tolerance=50,policy-regex-filter=🇸🇬|SG|sg|Singapore|新加坡|狮城|新
其他 = select,url=http://www.gstatic.com/generate_204,interval=600,timeout=5,tolerance=50,policy-regex-filter=^(?!.*(剩余|流量|套餐|到期|使用|文档|最新|网址|官网|更新|订阅|地址|客服|群|TG|公告|版本|维护|防失联|返利|移动夜间推荐|正常计费区)).*$
[Rule]

# 广告
RULE-SET,https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ads-all.list,广告

# 解锁
RULE-SET,https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/unlock.list,解锁

# 国内直连
RULE-SET,https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/direct.list,国内

# 国外代理
RULE-SET,https://github.com/Noah-Oliver/proxy-rule/raw/main/clash%20rule/proxy.list,国外

# GFW
RULE-SET,https://github.com/Loyalsoldier/clash-rules/raw/release/gfw.txt,国外

# 最终规则
FINAL,国内

[Host]
localhost = 127.0.0.1
